# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20160729_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlog',
            name='op',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\xbb\x8f\xe5\x8a\x9e\xe4\xba\xba'),
        ),
        migrations.AlterField(
            model_name='hostlog',
            name='peo',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xb3\xe8\xaf\xb7\xe4\xba\xba'),
        ),
    ]
