# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_hostlog_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlog',
            name='peo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='ops.Contact', verbose_name=b'\xe7\x94\xb3\xe8\xaf\xb7\xe4\xba\xba'),
        ),
    ]
