# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20160802_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlog',
            name='sn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Host', verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8sn'),
        ),
    ]
