# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='app_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='\u5e94\u7528\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='list',
            name='cpu',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='CPU\u6838\u5fc3\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='list',
            name='ip',
            field=models.GenericIPAddressField(db_index=True, null=True, verbose_name='IP\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='list',
            name='list_name',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='\u6e05\u5355\u4e3b\u673a\u540d'),
        ),
        migrations.AlterField(
            model_name='list',
            name='mem',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='\u5185\u5b58'),
        ),
        migrations.AlterField(
            model_name='list',
            name='total_hard_disk',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='\u603b\u786c\u76d8\u5bb9\u91cf'),
        ),
    ]
