# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostlog',
            name='notes',
            field=models.TextField(blank=True, max_length=254, null=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8'),
        ),
        migrations.AddField(
            model_name='hostlog',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=b'\xe4\xb8\x8a\xe6\xac\xa1\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='hostlog',
            name='born_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='hostlog',
            name='op',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe7\xbb\x8f\xe5\x8a\x9e\xe4\xba\xba'),
        ),
        migrations.AlterField(
            model_name='hostlog',
            name='sn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Host', verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8sn'),
        ),
    ]
