# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20160803_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostlog',
            name='sn',
        ),
        migrations.DeleteModel(
            name='HostLog',
        ),
    ]
