# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20160803_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born_time', models.DateTimeField(auto_created=True, default=datetime.datetime.now, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('state', models.CharField(choices=[('\u5728\u7528', '\u5728\u7528'), ('\u501f\u51fa', '\u501f\u51fa'), ('\u7ef4\u4fee', '\u7ef4\u4fee'), ('\u95f2\u7f6e', '\u95f2\u7f6e'), ('\u51fa\u5e93', '\u51fa\u5e93'), ('\u62a5\u5e9f', '\u62a5\u5e9f')], max_length=50, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('peo', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe7\x94\xb3\xe8\xaf\xb7\xe4\xba\xba')),
                ('op', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe7\xbb\x8f\xe5\x8a\x9e\xe4\xba\xba')),
                ('notes', models.TextField(blank=True, max_length=254, null=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name=b'\xe4\xb8\x8a\xe6\xac\xa1\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('sn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Host', verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8sn')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668\u53d8\u66f4\u8bb0\u5f55',
                'verbose_name_plural': '\u670d\u52a1\u5668\u53d8\u66f4\u8bb0\u5f55',
            },
        ),
    ]
