# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_hostlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlog',
            name='sn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Host', to_field=b'sn', verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8sn'),
        ),
        migrations.AlterField(
            model_name='hostlog',
            name='state',
            field=models.CharField(blank=True, choices=[('\u5728\u7528', '\u5728\u7528'), ('\u501f\u51fa', '\u501f\u51fa'), ('\u7ef4\u4fee', '\u7ef4\u4fee'), ('\u95f2\u7f6e', '\u95f2\u7f6e'), ('\u51fa\u5e93', '\u51fa\u5e93'), ('\u62a5\u5e9f', '\u62a5\u5e9f')], max_length=50, null=True, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81'),
        ),
    ]
