# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20160803_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostlog',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe7\x94\xb5\xe8\xaf\x9d'),
        ),
    ]
