# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmserver', '0005_listinfolog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='mem',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5185\u5b58'),
        ),
        migrations.AlterField(
            model_name='list',
            name='total_hard_disk',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u603b\u786c\u76d8\u5bb9\u91cf'),
        ),
    ]
